image: archlinux:latest

stages:
    - install_dependencies
    - formatting

before_script:
    - echo "Update packages"
    - pacman -Suy --noconfirm

install_dependencies:
    stage: install_dependencies
    tags:
        - Stylua
    script:
        - echo "Installing dependencies"
        - pacman -S --noconfirm stylua

formatting:
    stage: formatting
    tags:
        - Stylua
    script:
        - echo "Formatting with stylua"
        - stylua -v .