image: archlinux:latest

before_script:
    - echo "Update packages"
    - pacman -Suy --noconfirm

install_dependencies:
    script:
        - echo "Installing dependencies"
        - pacman -S --noconfirm stylua

formatting:
    script:
        - echo "Formatting with stylua"
        - stylua -v .
