image: "alpine:latest"

stages:
  - install_dependencies
  - install_domacsvim

install_dependencies:
    stage: install_dependencies
    script:
        - echo 'Installing DomacsVim dependencies.'
        - apk add yarn npm git nodejs neovim ripgrep build-base wget curl --update

install_domacsvim:
    stage: install_domacsvim
    script:
        - echo 'Installing DomacsVim'
        - curl -s 'https://gitlab.com/domacsvim/domacsvim/-/raw/V-1.0.0/installer/install.sh' >> domacsvim-install.sh
        - chmod +x ./domacsvim-install.sh
        - ./domacsvim-install.sh --no-install-dependencies