stages:
    - install_dependencies
    - formatting

install_dependencies:
    stage: install_dependencies
    tags:
        - Stylua
    script:
        - echo "Update packages"
        - pacman -Suy --noconfirm
        - echo "Installing dependencies"
        - pacman -S --noconfirm stylua

formatting:
    stage: formatting
    tags:
        - Stylua
    script:
        - echo "Formatting with stylua"
        - stylua -v .