stages:
  - install_dependencies
  - install_neovim
  - install_domacsvim
  - test

install_dependencies:
  stage: install_dependencies
  script:
      - echo 'Installing DomacsVim dependencies.'
      - apt-get update && apt-get install -y libssl-dev ninja-build gettext cmake unzip curl git

install_neovim:
  stage: install_neovim
  script:
    - echo 'Installing neovim'
    - cd ..
    - rm -rf neovim-master
    - wget https://github.com/neovim/neovim/archive/master.zip
    - unzip master.zip
    - rm -rf master.zip
    - cd neovim-master
    - make clean install

install_domacsvim:
  stage: install_domacsvim
  script:
      - echo 'Installing DomacsVim'
      - curl -s 'https://gitlab.com/domacsvim/domacsvim/-/raw/V-1.0.0/installer/install.sh' >> domacsvim-install.sh
      - chmod +x ./domacsvim-install.sh
      - ./domacsvim-install.sh --no-install-dependencies

test:
  stage: test
  script:
    - echo 'Testing DomacsVim'
    - /root/.local/bin/dvim --cmd ":qa!"
