name: Install on linux systems

on: [push, pull_request]

jobs:
  install_on_linux:
    name: install on linux
    runs-on: ubuntu-latest
    steps:
      - name: install_dependencies
      - run: echo 'Installing DomacsVim dependencies.'
      - run: apt-get update && apt-get install -y libssl-dev ninja-build gettext cmake unzip curl git

      - name: install_neovim
      - run: echo 'Installing neovim'
      - run: rm -rf neovim-master
      - run: wget https://github.com/neovim/neovim/archive/master.zip
      - run: unzip master.zip
      - run: rm -rf master.zip
      - run: cd neovim-master
      - run: make clean install

      - name: install_domacsvim
      - run: echo 'Installing DomacsVim'
      - run: curl -s 'https://gitlab.com/domacsvim/domacsvim/-/raw/V-1.0.0/installer/install.sh' >> domacsvim-install.sh
      - run: chmod +x ./domacsvim-install.sh
      - run: ./domacsvim-install.sh --no-install-dependencies

      - name: test
      - run: echo 'Testing DomacsVim'
      - run: /root/.local/bin/dvim --cmd ":qa!"
