on:
  pull_request:
    branches:
    - V-0.0.1

jobs:
  Formatting:
    name: "Formatting check with Stylua"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Formatting with stylua
        uses: JohnnyMorganz/stylua-action@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          version: latest
          args: --check .
