name: Stylua

on: push

jobs:
  build:
    runs-on: archlinux-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install stylua
        run: sudo pacman -S --noconfirm stylua
      - name: Formatting with stylua
        run: stylua --check .
