name: Stylua

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install stylua
        run: sudo apt -y install stylua
      - name: Formatting with stylua
        run: stylua --check .
