name: format

on:
  pull_request:
    branches:
      - "V-0.0.1"

jobs:
  stylua:
    name: Formatting check with stylua
    runs-on: ubutu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Formatting check with stylua
      uses: JohnnyMorganz/stylua-action@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          version: 0.15.3
          args: --check .
