on:
  pull_request:
    branches:
    - V-0.0.1
jobs:
  stylua-check:
    name: "Formatting check with Stylua"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          version: 0.15.3
          args: --check .

